name: Lab 2 - Branch Thinking
on:
  push:
    branches: [main, dev]

jobs:
  BranchTest:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Always Run
        run: echo "This step runs; on every push to main or dev"

      - name: 3. Main only Step
        if: github.ref == 'refs/heads/main'
        run: echo "This step runs only on pushes to main"

      - name: 4. Dev only Step
        if: github.ref == 'refs/heads/dev'
        run: echo "This step runs only on pushes to dev"

      - name: 5. Show Current Time
        run: date

      - name: 6. Show Current User
        run: whoami