name: My Lab 1 

on: [push]

jobs:
  WelcomeJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print My Goal
        run: echo "Lab 1 finished"

      - name: Show Current Time
        run: date