name: Lab 3 - Quality Control
on: [push]

jobs:
  QualityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Code Linting ( Simulated )
        run: |
          echo "Checking code style ..."
          sleep 2
          echo "Code Style is prefect!"
        
      - name: 3. Run Unit Tests
        run: |
          echo "Running tests ..."
          exit 0

      - name: 4. Deployment ( only if tests pass )
        run: echo "Tests passed ! Deploying to server ..."