name: Lab 4 - Docker Dry run
on: [push]

jobs:
  DockerCheck:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4
      
      - name: 2. Verify Docker Version
        run: docker --version

      - name: 3. Build Docker Image ( Dry Run )
        run: |
          echo "Starting Docker build process ..."
          docker build -t my-test-app:${{ github.sha }} .
          echo "Docker Build completed successfully !"

      - name: 4. Check Build Image
        run: docker images